kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: <namespace>
  name: readnamespacesrole
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: readnamespacesrolebinding
  namespace: <namespace>
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
    namespace: <namespace>
roleRef:
  kind: ClusterRole
  name: readnamespacesrole
  apiGroup: rbac.authorization.k8s.io